### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by alushingg** [AY1920S2-CS2103T-F10-4/main#129]

**Comment by dinhnhobao** [comment]
![image](https://user-images.githubusercontent.com/43085789/79069739-29548400-7d03-11ea-998f-4883d8ce85a7.png)
Should we do this `Effort` part?

**Comment by NNpanpan** [comment]
Can. Should be quick

**Comment by dinhnhobao** [comment]
Closed for `v1.4`.
