### ISSUE TITLE
DG Review by the tutor

### ISSUE THREAD

**Issue by RubaP** [AY1920S2-CS2103T-F10-4/main#177]
Overall you guys have done a good job. Some of the comments I have added for a figure is applicable to multiple figures. So it would be great if all of you in the team go through the comments and improve your own sections. Otherwise Kudos to the entire team. Keep up the good work

-  [Figure 2] What is happening here? Why do you need two parsers for each command and parent **creates** child?

![image](https://user-images.githubusercontent.com/5234584/78449016-cfbddb00-76ac-11ea-9639-b2fa147c6815.png)

- [Figure 4] Since the overall goal in the design section is to convey the design, you do not need to always have class diagrams to convey the low-level details. It may make the diagram complicate and difficult to understand. Instead, you can still have architecture-like diagram to show the inter-connection of sub-componenents of a component and for the selected sub-component you can elaborate more with a class diagram. You dont need to stick to the exact format of AB3 DG especially for the decisions on UML diagram type you want  

- [Figure 4 & 5] Why there are multiple formattings used to draw the diagram

- [Figure 9] Multiple arrows in a flow do not adhere to the standard UML. You may avoid it.

![image](https://user-images.githubusercontent.com/5234584/78450096-b1f17580-76ae-11ea-8b9f-35821ca4abe9.png)

- [Figure 9 & 13] Does your system show an error message during else path. Then you may have it before reaching the merge node

![image](https://user-images.githubusercontent.com/5234584/78450183-55db2100-76af-11ea-9eb1-ce4ad9f263d1.png)

- [Figure 11] So finally doesnt the system show the list of modules?

![image](https://user-images.githubusercontent.com/5234584/78450384-d0587080-76b0-11ea-80d5-5782facca709.png)

- [Figure 13] Why do you need the activities to be repeated. You may have a merge node since the rest of the flow is same for both if and else paths

![image](https://user-images.githubusercontent.com/5234584/78450231-c124f300-76af-11ea-8669-32c6e3c3e314.png)

- [Figure 15] When the user execute the add lesson command, at the end, the lesson/lesson list should be saved. Why does the diagram says ModManager is saved?

![image](https://user-images.githubusercontent.com/5234584/78450338-78ba0500-76b0-11ea-8914-428b70714eff.png)

- [Figure 17] Doesnt the system shows the list of classes to the user?

![image](https://user-images.githubusercontent.com/5234584/78450401-ec5c1200-76b0-11ea-85fb-e53d5fa8d2c6.png)

- [Figure 19] Same issue here. Doesn't the system shows the list of results?

![image](https://user-images.githubusercontent.com/5234584/78450418-05fd5980-76b1-11ea-810b-84740d984a3a.png)

- [Figure 26] Why is there an empty object and lifeline?

![image](https://user-images.githubusercontent.com/5234584/78450520-a6537e00-76b1-11ea-9d00-57d8bcb85715.png)

- [Figure 27] Unless it is very important to highlight, you do not need to give exact wording translation of your if condition, which will be diffifult for the user to understand. Instead you can give a generic explanation.

![image](https://user-images.githubusercontent.com/5234584/78450550-f0d4fa80-76b1-11ea-8483-63ec5b82164f.png)

- [Appendix B] You may change the action to be singular since the you can only one module, task etc at a time. Otherwise it will give an idea, you system is supposed to allow adding list of module, task etc.

![image](https://user-images.githubusercontent.com/5234584/78450813-ce43e100-76b3-11ea-98d9-3e8e0c04c707.png)

- [Appendix B] What do you mean by this

![image](https://user-images.githubusercontent.com/5234584/78450835-09461480-76b4-11ea-91ad-fb490401a3ad.png)

- [Appendix C] If the system still displays an empty list, then this extension will not be valid and it comes under list all modules steps

![image](https://user-images.githubusercontent.com/5234584/78450866-4ad6bf80-76b4-11ea-9532-4c1f9c57141e.png)

- [Appendix D] What do you mean by noticeable sluggishness? Be specific

![image](https://user-images.githubusercontent.com/5234584/78450899-aacd6600-76b4-11ea-9afc-e7d542790001.png)

- [ Appendix D] These are constraints of the project which you can be conveyed as part of your value proposition. It is not an NRF. NRF should depict the functionalities with constraints under which the system will be implemented

![image](https://user-images.githubusercontent.com/5234584/78450932-db150480-76b4-11ea-8977-19991169084d.png)

- [Appendix D] It would be better if you can have your app-specific NRF

**Comment by dinhnhobao** [comment]
Thanks a lot for your feedback!
Closed for `v1.4`.
